import {Gray} from './shades';
import {Shade, ThemeVariables} from './types';

export const darkThemeVars = (
  accent: Shade,
  danger: Shade
): ThemeVariables => ({
  'fg': '#ffffff',
  'fg-accent': accent.palette[3],
  'fg-danger': danger.palette[3],
  'fg-disabled': Gray.palette[4],
  'bg': '#262b31',
  'bg-hover': Gray.palette[9],
  'bg-pressed': '#16191d',
  'bg-alt': '#2c333a',
  'border': Gray.palette[8],
  'border-accent': accent.palette[4],
  'border-danger': danger.palette[4],

  'fg-control': '#ffffff',
  'fg-control-disabled': Gray.palette[4],
  'bg-control': Gray.palette[8],
  'bg-control-hover': Gray.palette[7],
  'bg-control-pressed': Gray.palette[9],
  'border-control': Gray.palette[7],

  'fg-bold': '#000000',
  'bg-bold': Gray.palette[3],

  'link-fg': 'hsl(215 100% 80%)',
  'link-fg-visited': 'hsl(275 60% 75%)',
  'link-fg-hover': 'hsl(215 100% 90%)',
  'link-fg-pressed': 'hsl(30 100% 75%)',

  'shadow-color': 'rgb(0 0 0 / 0.5)',
  'shadow-elevation-1': '0 2px 5px rgb(0 0 0 / 0.5)',
  'shadow-elevation-2': '0 3px 8px rgb(0 0 0 / 0.5)',
  'shadow-elevation-3': '0 4px 10px rgb(0 0 0 / 0.5)',

  'button-fg': 'var(--fg)',
  'button-fg-disabled': 'var(--fg-disabled)',
  'button-bg': Gray.palette[8],
  'button-bg-hover': Gray.palette[7],
  'button-bg-pressed': Gray.palette[9],
  'button-bg-disabled': Gray.palette[9],
  'button-border': 'var(--button-bg)',
  'button-border-hover': 'var(--button-bg-hover)',
  'button-border-pressed': 'var(--button-bg-pressed)',
  'button-border-disabled': 'var(--button-bg-disabled)',

  'button-accent-fg': '#ffffff',
  'button-accent-fg-disabled': '#ffffffaa',
  'button-accent-bg': accent.palette[7],
  'button-accent-bg-hover': accent.palette[6],
  'button-accent-bg-pressed': accent.palette[8],
  'button-accent-bg-disabled': accent.disabled.darkButtonBg,
  'button-accent-border': 'var(--button-accent-bg)',
  'button-accent-border-hover': 'var(--button-accent-bg-hover)',
  'button-accent-border-pressed': 'var(--button-accent-bg-pressed)',
  'button-accent-border-disabled': 'var(--button-accent-bg-disabled)',

  'button-bold-fg': '#000000',
  'button-bold-fg-disabled': '#262b31',
  'button-bold-bg': Gray.palette[3],
  'button-bold-bg-hover': Gray.palette[2],
  'button-bold-bg-pressed': Gray.palette[4],
  'button-bold-bg-disabled': Gray.palette[6],
  'button-bold-border': 'var(--button-bold-bg)',
  'button-bold-border-hover': 'var(--button-bold-bg-hover)',
  'button-bold-border-pressed': 'var(--button-bold-bg-pressed)',
  'button-bold-border-disabled': 'var(--button-bold-bg-disabled)',

  'button-danger-fg': '#ffffff',
  'button-danger-fg-disabled': '#ffffffaa',
  'button-danger-bg': danger.palette[7],
  'button-danger-bg-hover': danger.palette[6],
  'button-danger-bg-pressed': danger.palette[8],
  'button-danger-bg-disabled': danger.disabled.darkButtonBg,
  'button-danger-border': 'var(--button-danger-bg)',
  'button-danger-border-hover': 'var(--button-danger-bg-hover)',
  'button-danger-border-pressed': 'var(--button-danger-bg-pressed)',
  'button-danger-border-disabled': 'var(--button-danger-bg-disabled)',

  'button-naked-fg': 'var(--fg)',
  'button-naked-fg-disabled': 'var(--fg-disabled)',
  'button-naked-bg': 'var(--bg)',
  'button-naked-bg-hover': 'var(--bg-hover)',
  'button-naked-bg-pressed': 'var(--bg-pressed)',
  'button-naked-bg-disabled': 'var(--bg)',
  'button-naked-border': 'var(--button-naked-bg)',
  'button-naked-border-hover': 'var(--button-naked-bg-hover)',
  'button-naked-border-pressed': 'var(--button-naked-bg-pressed)',
  'button-naked-border-disabled': 'var(--button-naked-bg-disabled)',

  'input-fg': 'var(--fg)',
  'input-fg-disabled': 'var(--fg-disabled)',
  'input-bg': 'var(--bg)',
  'input-bg-disabled': 'var(--input-bg)',
  'input-border': Gray.palette[6],
  'input-border-disabled': Gray.palette[8],
  'input-minimal-border': 'transparent',
  'input-minimal-border-disabled': 'transparent',

  'checkbox-fg': '#000000',
  'checkbox-fg-disabled': 'var(--bg)',
  'checkbox-bg': 'var(--bg)',
  'checkbox-bg-hover': 'var(--bg-hover)',
  'checkbox-bg-pressed': 'var(--bg-pressed)',
  'checkbox-bg-disabled': 'var(--checkbox-bg)',
  'checkbox-bg-checked': accent.palette[4],
  'checkbox-bg-checked-hover': accent.palette[3],
  'checkbox-bg-checked-pressed': accent.palette[5],
  'checkbox-bg-checked-disabled': Gray.palette[7],
  'checkbox-border': Gray.palette[6],
  'checkbox-border-hover': 'var(--checkbox-border)',
  'checkbox-border-pressed': 'var(--checkbox-border)',
  'checkbox-border-disabled': Gray.palette[8],
  'checkbox-border-checked': 'var(--checkbox-bg-checked)',
  'checkbox-border-checked-hover': 'var(--checkbox-bg-checked-hover)',
  'checkbox-border-checked-pressed': 'var(--checkbox-bg-checked-pressed)',
  'checkbox-border-checked-disabled': 'var(--checkbox-bg-checked-disabled)',

  'radio-fg': accent.palette[4],
  'radio-fg-disabled': Gray.palette[7],
  'radio-bg': 'var(--bg)',
  'radio-bg-hover': 'var(--bg-hover)',
  'radio-bg-pressed': 'var(--bg-pressed)',
  'radio-bg-disabled': 'var(--radio-bg)',
  'radio-bg-checked': 'var(--radio-bg)',
  'radio-bg-checked-hover': accent.palette[8],
  'radio-bg-checked-pressed': accent.palette[9],
  'radio-bg-checked-disabled': 'var(--radio-bg)',
  'radio-border': Gray.palette[6],
  'radio-border-hover': 'var(--radio-border)',
  'radio-border-pressed': 'var(--radio-border)',
  'radio-border-disabled': Gray.palette[8],
  'radio-border-checked': accent.palette[4],
  'radio-border-checked-hover': accent.palette[3],
  'radio-border-checked-pressed': accent.palette[5],
  'radio-border-checked-disabled': Gray.palette[7],

  'switch-fg': Gray.palette[6],
  'switch-fg-disabled': Gray.palette[7],
  'switch-fg-checked': '#000000',
  'switch-fg-checked-disabled': 'var(--bg)',
  'switch-bg': 'var(--bg)',
  'switch-bg-hover': 'var(--bg-hover)',
  'switch-bg-pressed': 'var(--bg-pressed)',
  'switch-bg-disabled': 'var(--switch-bg)',
  'switch-bg-checked': accent.palette[4],
  'switch-bg-checked-hover': accent.palette[3],
  'switch-bg-checked-pressed': accent.palette[5],
  'switch-bg-checked-disabled': Gray.palette[7],
  'switch-border': Gray.palette[6],
  'switch-border-hover': 'var(--switch-border)',
  'switch-border-pressed': 'var(--switch-border)',
  'switch-border-disabled': Gray.palette[8],
  'switch-border-checked': 'var(--switch-bg-checked)',
  'switch-border-checked-hover': 'var(--switch-bg-checked-hover)',
  'switch-border-checked-pressed': 'var(--switch-bg-checked-pressed)',
  'switch-border-checked-disabled': 'var(--switch-bg-checked-disabled)',

  'select-fg': 'var(--fg)',
  'select-fg-disabled': 'var(--fg-disabled)',
  'select-bg': 'var(--bg)',
  'select-bg-hover': 'var(--bg-hover)',
  'select-bg-disabled': 'var(--select-bg)',
  'select-border': Gray.palette[6],
  'select-border-disabled': Gray.palette[8],
  'select-minimal-border': 'transparent',
  'select-minimal-border-disabled': 'transparent',

  'menu-fg': '#ffffff',
  'menu-fg-disabled': Gray.palette[5],
  'menu-bg': Gray.palette[9],
  'menu-bg-selected': Gray.palette[8],
  'menu-separator': Gray.palette[8],

  'toolbar-fg': 'var(--fg-control)',
  'toolbar-item-fg': 'var(--toolbar-fg)',
  'toolbar-item-fg-selected': 'var(--toolbar-fg)',
  'toolbar-item-fg-disabled': 'var(--fg-control-disabled)',
  'toolbar-bg': 'var(--bg-control)',
  'toolbar-item-bg': 'var(--toolbar-bg)',
  'toolbar-item-bg-hover': 'var(--bg-control-hover)',
  'toolbar-item-bg-pressed': 'var(--bg-control-pressed)',
  'toolbar-item-bg-selected': accent.palette[7],
  'toolbar-item-bg-disabled': 'var(--toolbar-item-bg)',
  'toolbar-item-shadow-selected': 'inset 0 1px 3px rgb(0 0 0 / 0.85)',

  'focus-border': 'hsl(200 95% 55%)',
});
